USE [TotalizatorDB];
GO

CREATE TABLE [Results]
(
	[Id] INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL,
	[Coefficient] FLOAT NOT NULL,
	[SportEventId] INT REFERENCES [SportEvents] ([Id]) ON DELETE CASCADE NOT NULL
);
GO